### ISSUE TITLE
[YouTube Search Added] Try All Sources Feature to Search for Unrecognised Anime

### ISSUE THREAD

**Issue by ajtazer** [Carleslc/MyAnime#35]
For example i was trying to watch
[Attack On SkyTree](https://myanimelist.net/anime/35122/Shingeki_no_Kyotou)
not only this there are many other titles on MAL that are not shows but some Advertisements or some other cameo shot for any shows.
so i would be great if u could add a search all providers option to watch such titles, as ONA, OVA & Specials aren't Available everywhere.
Also Adding Youtube Channels that share Licensed Anime like [Muse Asia](https://www.youtube.com/channel/UCGbshtvS9t-8CW11W7TooQg) [Ani-One Asia](https://www.youtube.com/channel/UC0wNSTMWIL3qaorLx0jie6A) Would be Great..
_P.S. I shared Channels that stream in my country so those maybe different for u and others._

**Comment by Carleslc** [comment]
You mean a provider option to search all other providers? It would require quite a lot of work, and I don't know if it would be feasible or sufficiently useful.

The best you can try currently when you cannot find the episode with your usual providers is the Lucky or search engine providers ("I'm Feeling Ducky" or "Google"). If they can't help, then probably this "try all" provider wouldn't help either.

Another option if you can not find an anime in a provider is trying to use an alternative title from the anime settings, sometimes some providers don't use the canonical title of the series but you can find the anime using another title. You can set a specific provider and alternative title for every anime to handle those specific cases. Also useful when you're watching different series on different providers, so you don't need to change the default provider every time.

If it helps, there is also an accessibility shortcut to move between providers using the down arrow key and enter/space to select. Tab key also works to move between animes and configuration settings.

A YouTube search provider is a valid option. If some channel has it published then it should show up on the results page. It is currently not implemented because it fails a lot for common series for copyright issues and in most cases it would redirect to an unrelated video. However, it may work for those special shows so it would be a valid provider, only a not so reliable one.

Related to the suggested "try all" provider it is worth pointing out that for some providers it's practically impossible to know programmatically if the anime or episode is available until you actually visit the website with a browser. MyAnime tries to guess the URL for the selected provider, anime and episode, but for most of the providers it is agnostic if the URL actually redirects to the expected episode. It usually works well with the majority of series, but it is prone to fail if the anime is unpopular or is a special kind of show. For some specific providers MyAnime may know in advance if the anime is available if it does scraping for the provider search results (it currently does that for a couple providers without canonical titles or ids), but usually is hard to know if providers do not have a public API. It is harder if the website is too dynamic for scraping (so search results are not provided in the HTML but loaded with JS using a private API), and even harder if they use mechanisms to block external or non-browser requests (that's why sometimes MyAnime uses a search engine as a middle step trying to get the episode URL like in AnimeHeaven, MasterAnime and sometimes with 9Anime and other providers).

**Comment by Carleslc** [comment]
From now on YouTube provider is supported, redirecting you to the search results page.

I've updated also the "I'm Feeling Ducky" and "Google" queries.

They are not the most reliable providers but are a good fallback option.

I hope it works a bit better for those specials now.

**Comment by ajtazer** [comment]
Yeah, Thanks i Appreciate your hardwork man.. and i believe people who find this in future will love it too..
P.S. now that i think about it 😅that Try All Option wasn't something efficient..
